MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 48
    DEPTHS: [ 1, 1, 1, 1 ]
    SSM_D_STATE: 1
    IN_CHANS: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v4"
    PATCHEMBED: "v4"
#    NORM_LAYER: "ln3d"